#!/bin/sh
cp ../Source/Core/*.cpp .
cp ../Source/Interface/Linux/*.cpp .
cp ../Source/Core/*.h .
make clean
SN := $(shell hostname --short)
FN := $(frankc-iMac)
if [ $(SN) -eq $(FN) ]
then
	make -j 4
else
	make -j 8
fi